

Post http://localhost:3000/register
Content-Type: application/json

{
    "username": "Rozahmd",
    "email":"hamidiroza2002@gmail.com",
    "password": "RozaRoza1381!"
}

Post http://localhost:3000/login
Content-Type: application/json

{
    "emailOrUsername": "Admin",
    "password": "Admin"
}